repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.4
  hooks:
    # Run the linter.
    - id: ruff
      name: Lint code
    # Run the formatter.
    - id: ruff-format
      name: Format code

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0
  hooks:
    - id: mypy
      name: Check type 
  
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.2.0
  hooks:
    - id: gitleaks
  
- repo: https://github.com/semgrep/pre-commit
  rev: 'v1.109.0'
  hooks:
    - id: semgrep
      args: ['--config', 'auto', '--error', '--skip-unknown-extensions']